[package]
name = "touying"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["OrangeX4", "contributors"]
license = "MIT"
description = "A more efficient package for creating presentation slides in Typst."
repository = "https://github.com/touying-typ/touying"
exclude = ["examples"]