[package]
name = "touying"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["OrangeX4"]
license = "MIT"
description = "More efficient slides creation with Typst."
repository = "https://github.com/touying-typ/touying"
exclude = ["examples"]